### ISSUE TITLE
一些小问题 / Little problems……

### ISSUE THREAD

**Issue by Stapxs** [Sneezry/Signpost#1]
1.如果我一不小心打开了一个以上，会导致系统卡顿
1. If I open more than one at the same time (accidentally), the system will be jammed.
2.由于全屏显示的实现方式，系统将会自动切换为免打扰模式
2. Due to the full-screen display, the system will automatically switch to the no-disturb mode

**Comment by Sneezry** [comment]
> 1.如果我一不小心打开了一个以上，会导致系统卡顿

Electron有API来控制单实例运行，后面我会加上，目前暂时可以通过系统栏里的图标来关闭多余的实例。

> 2.由于全屏显示的实现方式，系统将会自动切换为免打扰模式

这个我暂时还没有找到Electron提供什么方法可以避免，但是可以强制Windows开启或者关闭免打扰模式，目前可以在启动Signpost后，到Windows通知中心的控制面板切换免打扰模式：https://support.microsoft.com/en-us/help/4026996/windows-10-turn-focus-assist-on-or-off
